# Generated by Django 2.1 on 2018-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photograph', models.ImageField(upload_to='')),
                ('Photographer_FirstName', models.CharField(max_length=50)),
                ('Photographer_MiddleName', models.CharField(max_length=50)),
                ('Photographer_LastName', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Province', models.CharField(max_length=50)),
                ('County', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Year', models.IntegerField(max_length=4)),
                ('Season', models.CharField(max_length=20)),
                ('CoordinatesN', models.FloatField()),
                ('DateTaken', models.DateTimeField(blank=True, null=True)),
                ('Contributor_FirstName', models.CharField(max_length=50)),
                ('Contributor_LastName', models.CharField(max_length=50)),
                ('Contributor_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
