# Generated by Django 2.1 on 2018-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20180818_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='histimage',
            name='Contributor_Organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='histimage',
            name='CoordinatesE',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Contributor_Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Contributor_FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Contributor_LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='CoordinatesN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='County',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Photograph',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Photographer_FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Photographer_LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Photographer_MiddleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Season',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='histimage',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
