# Generated by Django 2.1 on 2018-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20180818_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histimage',
            name='Photograph',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
