# Generated by Django 2.1 on 2018-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20180818_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histimage',
            name='Photograph',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
