# Generated by Django 2.1 on 2018-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20180818_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histimage',
            name='Photograph',
            field=models.ImageField(blank=True, null=True, upload_to='history/photos'),
        ),
    ]
